#! /bin/bash
#
# Building and installing NETCDF and HDF5 as required by LROSE
# ============================================================
#
# The latest tar files reside in the 'tar_files' subdirectory.
#
# By default the target install directory is /usr/local,
# so that libraries and applications will be installed in:
#
#   /usr/local/include
#   /usr/local/lib
#   /usr/local/bin
#
# If you need to support packages other than LROSE, it is a good
# idea to install into /usr/local.
#
# If you are only supporting LROSE, you should install into the
# directory into which LROSE will be built and installed,
# for example:
#
#  $HOME/lrose
#  /usr/local/lrose
#
# You can change the install location by specifying it as
# a single argument to this script.
#
# For example:
#
#   build_and_install_netcdf $HOME/lrose
#
# will install in:
#
#   $HOME/lrose/include
#   $HOME/lrose/lib
#   $HOME/lrose/bin
#

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Usage: build_and_install_netcdf [ -h ] [ prefix ]"
    echo
    echo "  -h: produce this usage list"
    echo "  optionally set the prefix"
    echo
}

# set the path

#export PATH=.:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin

# set the install prefix

prefix=/usr/local

if [ $# -gt 0 ]
then
  if [ "$1" == -h -o "$2" == -h ] 
  then
    usage
    exit 0
  fi
  prefix=$1
fi

echo "Installing in prefix: $prefix"

# start in the netcdf_tar_files directory

cd tar_files || exit 1

#  Building HDF5
#  -------------

tar xvfz hdf5-*.tar.gz    # this may untar over a previous directory
cd hdf5-*/
export FC=gfortran
export F90=gfortran
export F77=gfortran
./configure --prefix=${prefix} --enable-cxx --enable-fortran || exit 1
make clean || exit 1  # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

# Building udunits2
# -----------------

tar xvfz udunits-*.tar.gz # this may untar over a previous directory
cd udunits-*/
./configure --prefix=${prefix} || exit 1
make clean || exit 1  # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

# When building the netCDF libraries below, make sure we use
# the hdf5 libraries we installed above

export CPPFLAGS=-I${prefix}/include
export LDFLAGS="-L${prefix}/lib -Wl,-rpath=${prefix}/lib"

# Building netcdf C
# -----------------

tar xvfz netcdf-4*.tar.gz # this may untar over a previous directory
cd netcdf-4*/
./configure --enable-netcdf4 --enable-shared --prefix=${prefix} || exit 1
make clean || exit 1  # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

# ---------------------------
# append USE_NETCDF4 to FLAGS

export CFLAGS="$CFLAGS -DUSE_NETCDF4"
export CPPFLAGS="$CPPFLAGS -DUSE_NETCDF4"
export LDFLAGS="$LDFLAGS -DUSE_NETCDF4"
 
# Building netcdf Fortran
# ------------------------

tar xvfz netcdf-fortran*.tar.gz # this may untar over a previous directory
cd netcdf-fortran*/
./configure --enable-shared --prefix=${prefix} || exit 1
make clean || exit 1        # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

# Building netcdf C++ legacy
# --------------------------

tar xvfz netcdf-cxx-4*.tar.gz # this may untar over a previous directory
cd netcdf-cxx-4*/
./configure --enable-shared --prefix=${prefix} || exit 1
make clean || exit 1      # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

# Building netcdf C++ 4
# ---------------------

tar xvfz netcdf-cxx4-4*.tar.gz  # this may untar over a previous directory
cd netcdf-cxx4-4*/
./configure --enable-shared --prefix=${prefix} || exit 1
make clean || exit 1        # remove files from previous builds, if any
make -j 8 || exit 1
make install || exit 1
cd ..

